"""Printable calibration board generation for LensU."""

from __future__ import annotations

import io
import zlib
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np


MM_TO_POINTS = 72.0 / 25.4
PAGE_SIZES = {
    "A4": (210.0 * MM_TO_POINTS, 297.0 * MM_TO_POINTS),
    "A3": (297.0 * MM_TO_POINTS, 420.0 * MM_TO_POINTS),
    "A2": (420.0 * MM_TO_POINTS, 594.0 * MM_TO_POINTS),
    "A1": (594.0 * MM_TO_POINTS, 841.0 * MM_TO_POINTS),
}


def _reportlab() -> tuple[object, object]:
    try:
        from reportlab.lib.utils import ImageReader
        from reportlab.pdfgen import canvas
    except ModuleNotFoundError as exc:
        raise RuntimeError("reportlab is required for PDF generation. Install it with `pip install reportlab`.") from exc
    return canvas, ImageReader


def _escape_pdf_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _pdf_stream(dictionary: str, payload: bytes) -> bytes:
    return (
        f"<< {dictionary} /Length {len(payload)} >>\nstream\n".encode("latin-1")
        + payload
        + b"\nendstream"
    )


def _write_simple_pdf(
    output_path: Path,
    page_width: float,
    page_height: float,
    content_commands: list[str],
    image: np.ndarray | None = None,
) -> Path:
    objects: list[bytes] = []

    def reserve() -> int:
        objects.append(b"")
        return len(objects)

    def set_object(object_id: int, payload: bytes | str) -> None:
        objects[object_id - 1] = payload.encode("latin-1") if isinstance(payload, str) else payload

    font_id = reserve()
    image_id = reserve() if image is not None else 0
    content_id = reserve()
    pages_id = reserve()
    page_id = reserve()
    catalog_id = reserve()

    set_object(font_id, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    if image is not None:
        if image.ndim == 2:
            colorspace = "/DeviceGray"
            raw = image.tobytes()
        else:
            colorspace = "/DeviceRGB"
            raw = image.tobytes()
        compressed = zlib.compress(raw)
        set_object(
            image_id,
            _pdf_stream(
                f"/Type /XObject /Subtype /Image /Width {image.shape[1]} /Height {image.shape[0]} "
                f"/ColorSpace {colorspace} /BitsPerComponent 8 /Filter /FlateDecode",
                compressed,
            ),
        )

    content_payload = "".join(content_commands).encode("latin-1")
    set_object(content_id, _pdf_stream("/Filter /FlateDecode", zlib.compress(content_payload)))

    resources = f"/Font << /F1 {font_id} 0 R >>"
    if image is not None:
        resources += f" /XObject << /Im1 {image_id} 0 R >>"
    set_object(pages_id, f"<< /Type /Pages /Kids [{page_id} 0 R] /Count 1 >>")
    set_object(
        page_id,
        f"<< /Type /Page /Parent {pages_id} 0 R /MediaBox [0 0 {page_width:.3f} {page_height:.3f}] "
        f"/Resources << {resources} >> /Contents {content_id} 0 R >>",
    )
    set_object(catalog_id, f"<< /Type /Catalog /Pages {pages_id} 0 R >>")

    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("latin-1"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    startxref = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("latin-1"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root {catalog_id} 0 R >>\nstartxref\n{startxref}\n%%EOF\n".encode(
            "latin-1"
        )
    )
    output_path.write_bytes(bytes(pdf))
    return output_path


def _page_size_to_points(page_size: str) -> tuple[float, float]:
    key = page_size.strip().upper()
    if key in PAGE_SIZES:
        return PAGE_SIZES[key]

    normalized = key.replace("MM", "").replace(" ", "")
    if "X" in normalized:
        width_mm, height_mm = (float(part) for part in normalized.split("X", maxsplit=1))
        return width_mm * MM_TO_POINTS, height_mm * MM_TO_POINTS

    raise ValueError(f"Unsupported page size: {page_size}")


def _metadata_lines(details: list[str]) -> list[str]:
    stamp = datetime.now().strftime("%Y-%m-%d")
    return [*details, "Generated by LensU", stamp]


def _draw_metadata(pdf: object, lines: list[str], margin_pt: float, page_width: float, page_height: float) -> None:
    text = pdf.beginText()
    text.setTextOrigin(margin_pt, margin_pt * 0.7)
    text.setFont("Helvetica", 9)
    for line in lines:
        text.textLine(line)
    pdf.drawText(text)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawRightString(page_width - margin_pt, page_height - margin_pt * 0.5, "LensU calibration board")


def _simple_metadata_commands(
    lines: list[str], margin_pt: float, page_width: float, page_height: float
) -> list[str]:
    commands: list[str] = []
    y = margin_pt * 0.7
    for line in lines:
        commands.append(f"BT /F1 9 Tf {margin_pt:.3f} {y:.3f} Td ({_escape_pdf_text(line)}) Tj ET\n")
        y += 11.0
    commands.append(
        f"BT /F1 10 Tf {page_width - margin_pt - 120.0:.3f} {page_height - margin_pt * 0.5:.3f} Td "
        f"({_escape_pdf_text('LensU calibration board')}) Tj ET\n"
    )
    return commands


def _centered_origin(
    page_width: float,
    page_height: float,
    board_width_pt: float,
    board_height_pt: float,
    margin_pt: float,
    metadata_height_pt: float,
) -> tuple[float, float]:
    available_width = page_width - 2 * margin_pt
    available_height = page_height - (2 * margin_pt) - metadata_height_pt
    if board_width_pt > available_width or board_height_pt > available_height:
        raise ValueError("Board does not fit on the selected page size.")

    origin_x = (page_width - board_width_pt) / 2.0
    origin_y = margin_pt + metadata_height_pt + (available_height - board_height_pt) / 2.0
    return origin_x, origin_y


def _encode_png(image: np.ndarray) -> object:
    _, ImageReader = _reportlab()
    success, encoded = cv2.imencode(".png", image)
    if not success:
        raise RuntimeError("Failed to encode board image.")
    return ImageReader(io.BytesIO(encoded.tobytes()))


def generate_checkerboard_pdf(
    pattern_size: tuple[int, int] = (9, 6),
    square_size_mm: float = 25.0,
    page_size: str = "A3",
    output_path: Path = Path("checkerboard.pdf"),
    include_metadata: bool = True,
) -> Path:
    """Generate a printable checkerboard calibration board as PDF."""

    inner_cols, inner_rows = pattern_size
    if inner_cols < 2 or inner_rows < 2:
        raise ValueError("Checkerboard pattern size must be at least 2x2 inner corners.")
    if square_size_mm <= 0:
        raise ValueError("Square size must be positive.")

    squares_x = inner_cols + 1
    squares_y = inner_rows + 1
    page_width, page_height = _page_size_to_points(page_size)
    board_width_pt = squares_x * square_size_mm * MM_TO_POINTS
    board_height_pt = squares_y * square_size_mm * MM_TO_POINTS
    margin_pt = 12.0 * MM_TO_POINTS
    metadata_height_pt = 24.0 * MM_TO_POINTS if include_metadata else 0.0
    origin_x, origin_y = _centered_origin(
        page_width,
        page_height,
        board_width_pt,
        board_height_pt,
        margin_pt,
        metadata_height_pt,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    square_pt = square_size_mm * MM_TO_POINTS
    metadata_lines = _metadata_lines(
        [
            f"Checkerboard inner corners: {inner_cols} x {inner_rows}",
            f"Square size: {square_size_mm:.2f} mm",
            f"Page size: {page_size.upper()}",
        ]
    )
    try:
        canvas, _ = _reportlab()
        pdf = canvas.Canvas(str(output_path), pagesize=(page_width, page_height))
        pdf.setTitle("LensU Checkerboard")
        pdf.setAuthor("LensU")
        pdf.setSubject("Printable checkerboard calibration board")
        pdf.setFillColorRGB(1, 1, 1)
        pdf.rect(0, 0, page_width, page_height, fill=1, stroke=0)
        pdf.setFillColorRGB(0, 0, 0)
        for row in range(squares_y):
            for col in range(squares_x):
                if (row + col) % 2 == 0:
                    x = origin_x + col * square_pt
                    y = origin_y + (squares_y - 1 - row) * square_pt
                    pdf.rect(x, y, square_pt, square_pt, fill=1, stroke=0)
        if include_metadata:
            _draw_metadata(pdf, metadata_lines, margin_pt, page_width, page_height)
        pdf.showPage()
        pdf.save()
        return output_path
    except RuntimeError:
        commands = [f"1 1 1 rg 0 0 {page_width:.3f} {page_height:.3f} re f\n", "0 0 0 rg\n"]
        for row in range(squares_y):
            for col in range(squares_x):
                if (row + col) % 2 == 0:
                    x = origin_x + col * square_pt
                    y = origin_y + (squares_y - 1 - row) * square_pt
                    commands.append(f"{x:.3f} {y:.3f} {square_pt:.3f} {square_pt:.3f} re f\n")
        if include_metadata:
            commands.extend(_simple_metadata_commands(metadata_lines, margin_pt, page_width, page_height))
        return _write_simple_pdf(output_path, page_width, page_height, commands)


def generate_charuco_pdf(
    board_size: tuple[int, int] = (7, 5),
    square_length_mm: float = 30.0,
    marker_length_mm: float = 22.5,
    dictionary: int = cv2.aruco.DICT_6X6_250 if hasattr(cv2, "aruco") else 0,
    page_size: str = "A3",
    output_path: Path = Path("charuco.pdf"),
    include_metadata: bool = True,
) -> Path:
    """Generate a printable ChArUco calibration board as PDF."""

    if not hasattr(cv2, "aruco"):
        raise RuntimeError("This OpenCV build does not include cv2.aruco.")
    if square_length_mm <= 0 or marker_length_mm <= 0:
        raise ValueError("Square and marker lengths must be positive.")
    if marker_length_mm >= square_length_mm:
        raise ValueError("Marker length must be smaller than square length.")

    page_width, page_height = _page_size_to_points(page_size)
    board_width_pt = board_size[0] * square_length_mm * MM_TO_POINTS
    board_height_pt = board_size[1] * square_length_mm * MM_TO_POINTS
    margin_pt = 12.0 * MM_TO_POINTS
    metadata_height_pt = 24.0 * MM_TO_POINTS if include_metadata else 0.0
    origin_x, origin_y = _centered_origin(
        page_width,
        page_height,
        board_width_pt,
        board_height_pt,
        margin_pt,
        metadata_height_pt,
    )

    aruco = cv2.aruco
    dictionary_obj = aruco.getPredefinedDictionary(dictionary)
    if hasattr(aruco, "CharucoBoard"):
        board = aruco.CharucoBoard(board_size, square_length_mm, marker_length_mm, dictionary_obj)
    elif hasattr(aruco, "CharucoBoard_create"):
        board = aruco.CharucoBoard_create(
            board_size[0],
            board_size[1],
            square_length_mm,
            marker_length_mm,
            dictionary_obj,
        )
    else:
        raise RuntimeError("This OpenCV build does not expose a ChArUco board constructor.")

    px_per_mm = 16
    board_px_size = (int(round(board_size[0] * square_length_mm * px_per_mm)), int(round(board_size[1] * square_length_mm * px_per_mm)))
    if hasattr(board, "generateImage"):
        board_image = board.generateImage(board_px_size, marginSize=0, borderBits=1)
    else:
        board_image = board.draw(board_px_size, marginSize=0, borderBits=1)
    board_rgb = cv2.cvtColor(board_image, cv2.COLOR_GRAY2RGB)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_lines = _metadata_lines(
        [
            f"ChArUco squares: {board_size[0]} x {board_size[1]}",
            f"Square length: {square_length_mm:.2f} mm",
            f"Marker length: {marker_length_mm:.2f} mm",
            f"Page size: {page_size.upper()}",
        ]
    )
    try:
        canvas, _ = _reportlab()
        pdf = canvas.Canvas(str(output_path), pagesize=(page_width, page_height))
        pdf.setTitle("LensU ChArUco")
        pdf.setAuthor("LensU")
        pdf.setSubject("Printable ChArUco calibration board")
        pdf.setFillColorRGB(1, 1, 1)
        pdf.rect(0, 0, page_width, page_height, fill=1, stroke=0)
        pdf.drawImage(
            _encode_png(board_rgb),
            origin_x,
            origin_y,
            width=board_width_pt,
            height=board_height_pt,
            preserveAspectRatio=True,
            mask="auto",
        )
        if include_metadata:
            _draw_metadata(pdf, metadata_lines, margin_pt, page_width, page_height)
        pdf.showPage()
        pdf.save()
        return output_path
    except RuntimeError:
        commands = [f"1 1 1 rg 0 0 {page_width:.3f} {page_height:.3f} re f\n"]
        commands.append(
            f"q {board_width_pt:.3f} 0 0 {board_height_pt:.3f} {origin_x:.3f} {origin_y:.3f} cm /Im1 Do Q\n"
        )
        if include_metadata:
            commands.extend(_simple_metadata_commands(metadata_lines, margin_pt, page_width, page_height))
        return _write_simple_pdf(output_path, page_width, page_height, commands, image=board_rgb)
