"""LensU — Unreal Engine export module.

Generates:
1. A calibration JSON file with all lens data
2. A UE Python script that creates a .ulens asset from the JSON
"""

import json
from pathlib import Path
from calibration import LensProfile


def export_ue_json(profile: LensProfile, output_path: Path) -> Path:
    """Export lens profile as UE-compatible JSON."""
    
    ue_data = {
        "lens_info": {
            "lens_name": profile.lens_name,
            "sensor_width_mm": profile.sensor_width_mm,
            "sensor_height_mm": profile.sensor_height_mm,
            "image_width": profile.image_width,
            "image_height": profile.image_height,
        },
        "distortion_table": [],
        "focal_length_table": [],
        "image_center_table": [],
        "nodal_offset_table": [],
    }

    for point in profile.calibration_points:
        # Focus=0 (infinity), Zoom=focal_length (UE convention)
        focus = 0.0
        zoom = point.focal_length_mm

        ue_data["distortion_table"].append({
            "focus": focus,
            "zoom": zoom,
            "distortion_info": {
                "parameters": [point.k1, point.k2, point.p1, point.p2, point.k3],
            },
            "focal_length_info": {
                "fx": point.fx,
                "fy": point.fy,
            },
        })

        ue_data["focal_length_table"].append({
            "focus": focus,
            "zoom": zoom,
            "focal_length_info": {
                "fx": point.fx,
                "fy": point.fy,
            },
        })

        ue_data["image_center_table"].append({
            "focus": focus,
            "zoom": zoom,
            "image_center": {
                "cx": point.cx,
                "cy": point.cy,
            },
        })

    for offset in profile.nodal_offsets:
        focus = 0.0
        zoom = offset.focal_length_mm

        ue_data["nodal_offset_table"].append({
            "focus": focus,
            "zoom": zoom,
            "offset": {
                "location_x": offset.offset_x,
                "location_y": offset.offset_y,
                "location_z": offset.offset_z,
                "rotation_x": offset.rotation_x,
                "rotation_y": offset.rotation_y,
                "rotation_z": offset.rotation_z,
            },
        })

    json_path = output_path / f"{profile.lens_name.replace(' ', '_')}_calibration.json"
    json_path.write_text(json.dumps(ue_data, indent=2))
    return json_path


def export_ue_python_script(profile: LensProfile, json_filename: str, output_path: Path) -> Path:
    """Generate a UE Python script that imports the JSON into a .ulens asset.
    
    This script is meant to be run inside UE's Python console or via
    Edit > Developer Tools > Python (UE 5.6+).
    """
    
    script = f'''"""
LensU — Auto-generated Unreal Engine import script
Lens: {profile.lens_name}
Generated by LensU

Instructions:
1. Copy this script and the JSON file to your UE project
2. Open UE Editor > Tools > Execute Python Script (or Python console)
3. Run this script — it will create a LensFile asset in /Game/LensU/

Requires: Camera Calibration plugin enabled
Compatible with: UE 5.6+
"""

import unreal
import json
import os

# --- Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(SCRIPT_DIR, "{json_filename}")
ASSET_NAME = "{profile.lens_name.replace(' ', '_')}"
ASSET_PATH = f"/Game/LensU/{{ASSET_NAME}}"


def create_lens_file():
    """Create a ULensFile asset from LensU calibration data."""

    # Load calibration JSON
    with open(JSON_PATH, "r") as f:
        data = json.load(f)

    # Create the asset
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    lens_file = asset_tools.create_asset(
        asset_name=ASSET_NAME,
        package_path="/Game/LensU",
        asset_class=unreal.LensFile,
        factory=unreal.LensFileFactory(),
    )

    if lens_file is None:
        unreal.log_error("Failed to create LensFile asset")
        return

    # Set lens info
    lens_info = data.get("lens_info", {{}})
    unreal.log(f"Importing lens: {{lens_info.get('lens_name', 'Unknown')}}")

    # Import distortion data
    for entry in data.get("distortion_table", []):
        focus = entry["focus"]
        zoom = entry["zoom"]
        params = entry["distortion_info"]["parameters"]
        fl = entry["focal_length_info"]

        distortion_info = unreal.DistortionInfo()
        distortion_info.parameters = params

        focal_length_info = unreal.FocalLengthInfo()
        focal_length_info.fx_fy = unreal.Vector2D(fl["fx"], fl["fy"])

        lens_file.add_distortion_point(focus, zoom, distortion_info, focal_length_info)

    # Import focal length data
    for entry in data.get("focal_length_table", []):
        focus = entry["focus"]
        zoom = entry["zoom"]
        fl = entry["focal_length_info"]

        focal_length_info = unreal.FocalLengthInfo()
        focal_length_info.fx_fy = unreal.Vector2D(fl["fx"], fl["fy"])

        lens_file.add_focal_length_point(focus, zoom, focal_length_info)

    # Import image center data
    for entry in data.get("image_center_table", []):
        focus = entry["focus"]
        zoom = entry["zoom"]
        center = entry["image_center"]

        image_center_info = unreal.ImageCenterInfo()
        image_center_info.principal_point = unreal.Vector2D(center["cx"], center["cy"])

        lens_file.add_image_center_point(focus, zoom, image_center_info)

    # Import nodal offset data
    for entry in data.get("nodal_offset_table", []):
        focus = entry["focus"]
        zoom = entry["zoom"]
        offset = entry["offset"]

        nodal_offset = unreal.NodalPointOffset()
        nodal_offset.location_offset = unreal.Vector(
            offset["location_x"],
            offset["location_y"],
            offset["location_z"],
        )
        nodal_offset.rotation_offset = unreal.Rotator(
            offset["rotation_x"],
            offset["rotation_y"],
            offset["rotation_z"],
        )

        lens_file.add_nodal_offset_point(focus, zoom, nodal_offset)

    # Save
    unreal.EditorAssetLibrary.save_asset(ASSET_PATH)
    unreal.log(f"LensFile created at {{ASSET_PATH}}")
    unreal.log(f"Distortion points: {{len(data.get('distortion_table', []))}}")
    unreal.log(f"Nodal offset points: {{len(data.get('nodal_offset_table', []))}}")


if __name__ == "__main__":
    create_lens_file()
'''

    script_path = output_path / f"import_{profile.lens_name.replace(' ', '_')}_to_ue.py"
    script_path.write_text(script)
    return script_path
